version: '2.2'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - 4000
    volumes:
      - '~/.gitconfig:/home/webdev/.gitconfig:ro'
      - '.:/www'
    working_dir: '/www'
    user: '1000:1000'
    command: '/bin/bash -i'
